{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.services.elogind;

  format = pkgs.formats.systemd { };

  # generated here rather than inline in `environment.etc`, so the unit can name them without
  # reading them back out of `environment.etc` - which is where most implementations put the
  # unit itself, making it a definition in terms of itself
  loginConf = format.generate "logind.conf" { inherit (cfg.settings) Login; };
  sleepConf = format.generate "sleep.conf" { inherit (cfg.settings) Sleep; };
in
{
  imports = [
    ./providers.services.nix
    ./providers.resume-and-suspend.nix
  ];

  options.services.elogind = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [elogind](${pkgs.elogind.meta.homepage}) as a system service.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.elogind;
      defaultText = lib.literalExpression "pkgs.elogind";
      description = ''
        The package to use for `elogind`.
      '';
    };

    debug = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable debug logging.
      '';
    };

    settings.Login = lib.mkOption {
      type = (pkgs.formats.keyValue { }).type;
      default = { };
      description = ''
        `elogind` login manager configuration. See {manpage}`logind.conf(5)`
        for additional details.
      '';
    };

    settings.Sleep = lib.mkOption {
      type = (pkgs.formats.keyValue { }).type;
      default = { };
      description = ''
        `elogind` suspend and hibernation configuration. See {manpage}`sleep.conf(5)`
        for additional details.
      '';
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    loginConf = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = loginConf;
      description = "Generated by this module, named by its units.";
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    sleepConf = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = sleepConf;
      description = "Generated by this module, named by its units.";
    };
  };

  # a terminal waiting for elogind is stated by the getty module, which is what owns terminals
  # and knows how to say it in both lowerings - a finit condition on a tty stanza, a `requires`
  # on a contract unit. Said from here it could only be the former, so on every backend but
  # finit the ordering quietly did not exist.

  config = lib.mkIf cfg.enable {
    # `service/dbus/ready` is gone with the stanza: what this actually needed was not the bus
    # daemon being up but its socket answering, and the finit condition could only say the
    # former. The bus unit says the latter itself now - it is not ready until the socket is
    # there - so being in a later tier than it is the whole of what this needs.
    services.dbus.enable = true;
    services.dbus.packages = [ cfg.package ];
    services.udev.packages = [ cfg.package ];

    environment.systemPackages = [ cfg.package ];

    environment.etc."elogind/logind.conf.d/00-nixos.conf".source = loginConf;
    environment.etc."elogind/sleep.conf.d/00-nixos.conf".source = sleepConf;
  };
}
