{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.services.iwd;
  format = pkgs.formats.ini { };

  configFile = format.generate "main.conf" cfg.settings;
in
{
  imports = [ ./providers.services.nix ];

  options.services.iwd = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [iwd](${pkgs.iwd.meta.homepage}) as a system service.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.iwd;
      defaultText = lib.literalExpression "pkgs.iwd";
      description = ''
        The package to use for `iwd`.
      '';
    };

    debug = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable debug logging.
      '';
    };

    settings = lib.mkOption {
      type = format.type;
      default = { };
      description = ''
        `iwd` configuration. See {manpage}`iwd.config(5)`
        for additional details.
      '';
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    configFile = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = configFile;
      description = "Generated by this module, named by its units.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.iwd.settings = {
      General = {
        # upstream defaults this to false, expecting another service to own IP.
        # default it on so iwd works standalone, but let users hand IP
        # configuration to a dhcp client instead.
        EnableNetworkConfiguration = lib.mkDefault true;
      };

      Network = {
        NameResolvingService = if config.programs.resolvconf.enable then "resolvconf" else "none";
      };
    };

    environment.systemPackages = [ cfg.package ];
    environment.etc."iwd/main.conf".source = configFile;

    services.dbus.packages = [ cfg.package ];

  };
}
