{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.avahi;

  mkValueString =
    v:
    if v == true then
      "yes"
    else if v == false then
      "no"
    else
      lib.generators.mkValueStringDefault { } v;

  format = pkgs.formats.ini {
    mkKeyValue = lib.generators.mkKeyValueDefault { inherit mkValueString; } "=";
    listToValue = lib.concatMapStringsSep ", " mkValueString;
  };

  configFile = format.generate "avahi-daemon.conf" cfg.settings;

  enableDbus = cfg.settings.server.enable-dbus or true;
in
{
  imports = [ ./providers.services.nix ];

  options.services.avahi = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [avahi](${pkgs.avahi.meta.homepage}) as a system service.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.avahi;
      defaultText = lib.literalExpression "pkgs.avahi";
      description = ''
        The package to use for `avahi`.
      '';
    };

    debug = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable debug logging.
      '';
    };

    extraArgs = lib.mkOption {
      type = with lib.types; listOf str;
      default = [ ];
      description = ''
        Additional arguments to pass to `avahi`. See {manpage}`avahi-daemon(8)`
        for additional details.
      '';
    };

    settings = lib.mkOption {
      type = format.type;
      default = { };
      description = ''
        `avahi` configuration. See {manpage}`avahi-daemon.conf(5)`
        for additional details.
      '';
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    configFile = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = configFile;
      description = "Generated by this module, named by its units.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.avahi.extraArgs = [ "--syslog" ] ++ lib.optionals cfg.debug [ "--debug" ];
    services.avahi.settings = {
      server = { };
    };

    environment.systemPackages = [ cfg.package ];

    environment.etc."avahi/avahi-daemon.conf".source = configFile;

    services.dbus = lib.optionalAttrs enableDbus {
      enable = true;
      packages = [ cfg.package ];
    };

    users.users.avahi = {
      description = "avahi-daemon privilege separation user";
      home = "/var/empty";
      group = "avahi";
      isSystemUser = true;
    };

    users.groups.avahi = { };
  };
}
