# nixos-facter: a hardware report, turned into the handful of settings it implies.
#
# Imported explicitly rather than loaded by default, so `hardware.facter.*` exists only on a
# machine which has a report to hand it. `reportPath` is enough to arm it - `enable` follows
# from the report being non-empty.
#
# Ported from nixos. What arrives is the subset which writes into options this module tree
# actually has:
#
#   disk, keyboard        initrd kernel modules for the root disk and the keyboard
#   graphics              the gpu's modules, and hardware.graphics
#   firmware              redistributable firmware and cpu microcode
#   amd-cpu               the amd_pstate kernel parameters for the running kernel version
#   bluetooth             services.bluetooth, which is where nixos says hardware.bluetooth
#   fingerprint           services.fprintd, when the report names a device fprintd supports
#   virtualisation        kvm and virtio modules; guest additions are warned about, not set
#   system                nixpkgs.hostPlatform
#
# Four of nixos' files are not here, each because everything it writes is absent:
#
#   boot.nix              only sets boot.loader.grub.efiSupport, and there is no grub module
#   networking/           networking.useDHCP and networking.interfaces, which do not exist -
#                         dhcpcd here runs on every interface, which is what that was for
#   networking/intel.nix  networking.enableIntel2200BGFirmware; the 3945ABG half is covered
#                         by hardware.enableRedistributableFirmware being on by default below
#   camera/ipu6.nix       hardware.ipu6, no module
{
  lib,
  config,
  modules,
  ...
}:
{
  imports = [
    # firmware.nix writes `hardware.enableRedistributableFirmware`, which lives here. Brought
    # along rather than left to the importer: facter on its own would otherwise be a config
    # which does not evaluate.
    ../all-firmware.nix

    # The two service modules whose `enable` the submodules below write to. Declaring an
    # option is what makes writing to it legal, and each is still gated on its own enable -
    # so importing them costs a machine whose report names neither device nothing at all.
    #
    # nixos has both of these in its default module list, which is why its version of facter
    # can write to them without saying anything. Here nothing is loaded unasked.
    modules.bluetooth
    modules.fprintd

    ./amd-cpu.nix
    ./bluetooth.nix
    ./debug.nix
    ./disk.nix
    ./fingerprint
    ./firmware.nix
    ./graphics.nix
    ./keyboard.nix
    ./system.nix
    ./virtualisation.nix
  ];

  options.hardware.facter = with lib; {
    enable = mkOption {
      type = types.bool;
      default = config.hardware.facter.report != { };
      defaultText = literalExpression ''
        config.hardware.facter.report != { }
      '';
      description = ''
        Whether to enable automatic hardware configuration using a report generated by
        nixos-facter.

        See <https://nix-community.github.io/nixos-facter/> for more information.
      '';
    };

    report = mkOption {
      type = types.attrsOf types.anything;
      default =
        if config.hardware.facter.reportPath == null then
          { }
        else
          builtins.fromJSON (builtins.readFile config.hardware.facter.reportPath);
      defaultText = "A JSON import from config.hardware.facter.reportPath (if not null), {} otherwise.";
      description = ''
        Hardware report data generated by nixos-facter.

        See <https://nix-community.github.io/nixos-facter/> for more information.
      '';
    };

    reportPath = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = ''
        Path to a hardware report generated by nixos-facter.

        To generate a report, run the following as root:
        ```
        nix-shell -p nixos-facter --run nixos-facter > facter.json
        ```

        See <https://nix-community.github.io/nixos-facter/> for more information.
      '';
    };
  };
}
