{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.services.greetd;
  format = pkgs.formats.toml { };

  configFile = format.generate "greetd.toml" cfg.settings;

  session_rundir =
    if config.services.sessiond.enable then
      "session optional ${config.services.sessiond.package}/lib/security/pam_sessiond.so"
    else if config.services.elogind.enable then
      "session optional ${pkgs.elogind}/lib/security/pam_elogind.so"
    else if config.services.seatd.enable then
      "session optional ${pkgs.pam_rundir}/lib/security/pam_rundir.so"
    else
      false;
in
{
  imports = [ ./providers.services.nix ];

  options.services.greetd = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [greetd](${pkgs.greetd.meta.homepage}) as a system service.
      '';
    };

    settings = lib.mkOption {
      type = format.type;
      default = { };
      description = ''
        `greetd` configuration. See {manpage}`greetd(5)`
        for additional details.
      '';
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    configFile = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = configFile;
      description = "Generated by this module, named by its units.";
    };
  };

  config = lib.mkIf cfg.enable {

    services.greetd.settings = {
      terminal.vt = lib.mkDefault "next";
      default_session = {
        command = lib.mkDefault "${pkgs.greetd}/bin/agreety";
        user = "greeter";
      };
    };

    users.users = {
      greeter = {
        isSystemUser = true;
        group = "greeter";
        extraGroups = [
          "video"
        ]
        ++ lib.optionals config.services.elogind.enable [
          "render"
        ]
        ++ lib.optionals config.services.seatd.enable [
          config.services.seatd.group
        ];
      };
    };

    users.groups = {
      greeter = { };
    };

    security.pam = {
      enable = true;
      services.greetd.text = ''
        # Account management.
        account required pam_unix.so # unix (order 10900)

        # Authentication management.
        auth sufficient pam_unix.so likeauth nullok try_first_pass # unix (order 12800)
        auth required pam_deny.so # deny (order 13600)

        # Password management.
        password sufficient pam_unix.so nullok yescrypt # unix (order 10200)

        # Session management.
        session required pam_env.so conffile=/etc/security/pam_env.conf readenv=0 # env (order 10100)
        session required pam_unix.so # unix (order 10200)
        session required pam_loginuid.so # loginuid (order 10300)
        session required pam_limits.so

        ${lib.optionalString (session_rundir != false) session_rundir}
      '';
    };

    providers.services.tmpfiles.rules = [
      {
        type = "directory";
        path = "/var/cache/tuigreet";
        user = "greeter";
        group = "greeter";
      }
    ];
  };
}
