//! rc.init: the one child a thin init starts, which must never return.
//!
//! Neither sinit nor nxinit restarts this if it exits - neither takes any notice at all - so it
//! has to be the thing that stays alive, the way `runsvdir` is on runit.
//!
//! Everything it starts is a separate process rather than a thread, which is not an accident of
//! the port: `switch.activate` starts a unit after boot by running the same job again, from a
//! process that then exits, and that only works if a job was never anything but its own process
//! in the first place. Threads here would have made the running generation something only
//! rc.init could reach into, which is the supervisor this backend is trying not to have.
//!
//! Once every job is launched there is nothing left to do but reap. An anchor's or oneshot's job
//! exits as soon as it has latched, and would otherwise zombie under rc.init specifically, since
//! it is rc.init - not pid 1 - that is its parent for as long as rc.init keeps running.

use crate::latch::Latches;
use crate::manifest::Manifest;
use crate::proc;
use std::process::{Command, ExitCode};
use std::time::Duration;

pub fn run(manifest: &Manifest, manifest_path: &str) -> ExitCode {
    let latches = Latches::new(&manifest.latch_dir);
    if let Err(e) = latches.ensure() {
        eprintln!("finix-rc init: {}: {e}", manifest.latch_dir);
        return ExitCode::from(1);
    }

    // /proc/self/exe rather than a path baked into the manifest. The manifest is generated by
    // the same Nix expression that builds this binary, so it could carry it - but a job started
    // by the generation that is actually running should be this binary and not whichever one a
    // half-applied switch left named in a file.
    let Ok(exe) = std::env::current_exe() else {
        eprintln!("finix-rc init: cannot read /proc/self/exe, so jobs cannot be started");
        return ExitCode::from(1);
    };

    for (name, _) in manifest.boot_side() {
        let spawned = Command::new(&exe)
            .arg("job")
            .arg(manifest_path)
            .arg(name)
            .spawn();

        if let Err(e) = spawned {
            eprintln!("finix-rc init: {name}: {e}");
        }
    }

    // Blocks on whichever child finishes first and loops, rather than trying to wait for all of
    // them at once: a service's job never exits on its own, so there is no point at which they
    // could all be collected.
    //
    // `reap_one` returning false means there are no children left - every job was a oneshot or
    // an anchor and all of them are done. There is nothing further to do and this still must not
    // return, so it sleeps instead of spinning on an error.
    loop {
        if !proc::reap_one() {
            proc::sleep(Duration::from_secs(3600));
        }
    }
}
