{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.services.rsyslog;

  configFile = pkgs.writeText "rsyslog.conf" ''
    # Load necessary modules
    module(load="imuxsock")    # UNIX socket input (for local logging)
    module(load="imklog")      # Kernel log messages

    # Global settings
    $MaxMessageSize 64k
    $ModLoad immark
    $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
    $RepeatedMsgReduction on

    # Rate limiting
    $SystemLogRateLimitInterval 5
    $SystemLogRateLimitBurst 1000

    # Logging rules
    *.*;auth,authpriv.none      -/var/log/syslog
    auth,authpriv.*             -/var/log/auth.log
    kern.*                      -/var/log/kern.log
    mail.*                      -/var/log/mail.log
    cron.*                      -/var/log/cron.log
    daemon.*                    -/var/log/daemon.log
    user.*                      -/var/log/user.log
    *.emerg                     :omusrmsg:*
    *.alert                     -/var/log/alert.log

    $IncludeConfig /etc/rsyslog.d/*.conf
  '';
in
{
  imports = [ ./providers.services.nix ];

  options.services.rsyslog = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [rsyslog](${pkgs.rsyslog.meta.homepage}) as a system service.
      '';
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    configFile = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = configFile;
      description = "Generated by this module, named by its units.";
    };
  };

  config = lib.mkIf cfg.enable {
    # the two are alternatives under one name, so this one being on means the other is off.
    # Plain `false` rather than `mkForce`: it overrides a default, and a machine which asks
    # for sysklogd outright as well gets a conflict, which is what enabling two syslog daemons
    # deserves.
    services.sysklogd.enable = false;

    system.switch.inhibitors.syslogd = config.providers.services.units.syslogd.type.service.command;

    services.logrotate.rules.rsyslog = {
      text = ''
        /var/log/syslog
        /var/log/auth.log
        /var/log/kern.log
        /var/log/mail.log
        /var/log/cron.log
        /var/log/daemon.log
        /var/log/user.log
        /var/log/alert.log
        {
          rotate 7
          daily
          missingok
          notifempty
          compress
          delaycompress
          sharedscripts

          postrotate
            ${lib.getExe' config.programs.coreutils.package "kill"} -s HUP $(cat /run/rsyslog.pid)
          endscript
        }
      '';
    };
  };
}
