{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.services.dhcpcd;

  format =
    let
      format' = pkgs.formats.keyValue {
        listToValue = v: lib.concatMapStringsSep "," toString v;
        mkKeyValue = k: v: if v == true then k else "${k} ${toString v}";
      };
    in
    {
      type = format'.type;
      generate = name: value: format'.generate name (lib.filterAttrs (_: v: v != false) value);
    };
in
{
  options.services.dhcpcd = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [dhcpcd](${pkgs.dhcpcd.meta.homepage}) as a system service.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.dhcpcd.override {
        withUdev = config.services.udev.enable;
      };
      defaultText = lib.literalExpression ''
        pkgs.dhcpcd.override {
          withUdev = config.services.udev.enable;
        }
      '';
      description = ''
        The package to use for `dhcpcd`.
      '';
    };

    debug = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable debug logging.
      '';
    };

    extraArgs = lib.mkOption {
      type = with lib.types; listOf str;
      default = [ ];
      description = ''
        Additional arguments to pass to `dhcpcd`. See {manpage}`dhcpcd(8)`
        for additional details.
      '';
    };

    settings = lib.mkOption {
      type = lib.types.submodule {
        freeformType = format.type; # FIXME: types.record { }
        options = {
          # FIXME: why do booleans get turned into "1" if you don't declare them as booleans?

          broadcast = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Instructs the DHCP server to broadcast replies back to the client.
            '';
          };

          duid = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Use a DHCP Unique Identifier.
            '';
          };

          hostname = lib.mkOption {
            type = with lib.types; nullOr str;
            default = null;
            description = ''
              Sends the hostname name to the DHCP server so it can be registered in DNS.
            '';
          };

          hostname_short = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Sends the short hostname to the DHCP server instead of the FQDN.
            '';
          };

          ipv4only = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Only configure IPv4.
            '';
          };

          ipv6only = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Only configure IPv6.
            '';
          };

          noalias = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Any pre-existing IPv4 addresses will be removed from the interface when adding a new IPv4 address.
            '';
          };

          nogateway = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Don't install any default routes.
            '';
          };

          quiet = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Suppress any `dhcpcd` output to the console, except for errors.
            '';
          };

          waitip = lib.mkOption {
            type = with lib.types; nullOr bool;
            default = null;
            description = ''
              Wait for an address to be assigned before forking to the background.
            '';
          };
        };
      };
      default = { };
      description = ''
        `dhcpcd` configuration. See {manpage}`dhcpcd.conf(5)`
        for additional details.
      '';
    };

    configFile = lib.mkOption {
      type = lib.types.path;
      default = format.generate "dhcpcd.conf" (lib.filterAttrs (_: v: v != null) cfg.settings);
      defaultText = "configuration file generated by nixos";
    };
  };

  config = lib.mkIf cfg.enable {
    services.dhcpcd.extraArgs = [
      "-B"
      "-f"
      (toString cfg.configFile)
    ];

    services.dhcpcd.settings = {
      # Inform the DHCP server of our hostname for DDNS.
      hostname = "";

      # A list of options to request from the DHCP server.
      option = [
        "domain_name_servers"
        "domain_name"
        "domain_search"
        "host_name"
        "classless_static_routes"
        "ntp_servers"
        "interface_mtu"
      ];

      # A ServerID is required by RFC2131.
      # Commented out because of many non-compliant DHCP servers in the wild :(
      #require dhcp_server_identifier

      # A hook script is provided to lookup the hostname if not set by
      # the DHCP server, but it should not be run by default.
      nohook = "lookup-hostname";

      # Ignore peth* devices; on Xen, they're renamed physical
      # Ethernet cards used for bridging.  Likewise for vif* and tap*
      # (Xen) and virbr* and vnet* (libvirt).
      denyinterfaces = [
        "lo"
        "peth*"
        "vif*"
        "tap*"
        "tun*"
        "virbr*"
        "vnet*"
        "vboxnet*"
        "sit*"
      ];

      debug = cfg.debug;
    };

    providers.services.units.dhcpcd = {
      description = "dhcp client";

      type.service = {
        # PATH set in the command rather than asked for as a unit property: dinit has no
        # per-unit PATH, and dhcpcd needs resolvconf on it to write /etc/resolv.conf.
        command = pkgs.writeShellScript "dhcpcd" ''
          ${lib.optionalString config.programs.resolvconf.enable "export PATH=${config.programs.resolvconf.package}/bin:$PATH"}
          exec ${lib.getExe cfg.package} ${lib.escapeShellArgs cfg.extraArgs}
        '';

        readiness = "fork";
      };

      requires =
        lib.optional config.services.sysklogd.enable "syslogd"
        ++ lib.optional config.services.udev.enable "udev-settle";
    };

    providers.services.tmpfiles.rules = [
      {
        type = "directory";
        path = "/var/db/dhcpcd";
        user = "dhcpcd";
      }
      {
        type = "directory";
        path = "/var/lib/dhcpcd";
        user = "dhcpcd";
        group = "dhcpcd";
      }
    ];

    users.users = {
      dhcpcd = {
        group = "dhcpcd";
      };
    };

    users.groups = {
      dhcpcd = { };
    };
  };
}
