{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.services.sessiond-uaccess;

  configFile = pkgs.writeTextDir "00-nixos.lua" cfg.extraConfig;

  # gardendevd needs libudev-garden; mdevd/keventd need libudev-zero
  udevApi =
    if config.services.gardendevd.enable then
      pkgs.libudev-garden
    else if config.services.mdevd.enable || config.services.keventd.enable then
      pkgs.libudev-zero
    else
      null;
in
{
  imports = [ ./providers.services.nix ];

  options.services.sessiond-uaccess = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [sessiond](${pkgs.sessiond-uaccess.meta.homepage}) as a system service.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.sessiond-uaccess.override (
        lib.optionalAttrs (udevApi != null) {
          udev = udevApi;
        }
      );
      defaultText = lib.literalExpression "pkgs.sessiond-uaccess";
      description = ''
        The package to use for `sessiond`.
      '';
    };

    debug = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable debug logging.
      '';
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      example = ''
        device {
          access = "rw",
          match = function(dev)
            return dev.subsystem == "backlight"
          end,
        }
      '';
      description = ''
        Additional `lua` rules loaded after the packaged `sessiond-uaccess` rules. See [upstream documentation](https://tangled.org/r0chd.pl/sessiond-uaccess/blob/master/rules/70-uaccess.lua)
        for additional details.
      '';
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    configFile = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = configFile;
      description = "Generated by this module, named by its units.";
    };
  };

  config = lib.mkIf cfg.enable {
    # this watches sessiond's sessions over the bus and does nothing without it, so it turns
    # it on rather than ordering after a daemon which may not be there - the same thing
    # sessiond itself does with polkit
    services.sessiond.enable = true;

  };
}
