{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.services.blocky;

  format = pkgs.formats.yaml { };
  configFile = format.generate "config.yaml" cfg.settings;
in
{
  imports = [ ./providers.services.nix ];

  options.services.blocky = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [blocky](${pkgs.blocky.meta.homepage}) as a system service.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.blocky;
      defaultText = lib.literalExpression "pkgs.blocky";
      description = ''
        The package to use for `blocky`.
      '';
    };

    debug = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable debug logging.
      '';
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "blocky";
      description = ''
        User account under which `blocky` runs.

        ::: {.note}
        If left as the default value this user will automatically be created
        on system activation, otherwise you are responsible for
        ensuring the user exists before the `blocky` service starts.
        :::
      '';
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "blocky";
      description = ''
        Group account under which `blocky` runs.

        ::: {.note}
        If left as the default value this group will automatically be created
        on system activation, otherwise you are responsible for
        ensuring the group exists before the `blocky` service starts.
        :::
      '';
    };

    settings = lib.mkOption {
      type = format.type;
      default = { };
      description = ''
        `blocky` configuration. See [upstream documentation](https://0xerr0r.github.io/blocky/configuration)
        for additional details.
      '';
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    configFile = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = configFile;
      description = "Generated by this module, named by its units.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.blocky.settings = {
      log = {
        level = lib.mkIf cfg.debug "debug";
        timestamp = false;
      };

      queryLog.type = lib.mkDefault "none";
    };

    users.users = lib.mkIf (cfg.user == "blocky") {
      blocky = {
        isSystemUser = true;
        group = cfg.group;
      };
    };

    users.groups = lib.mkIf (cfg.group == "blocky") {
      blocky = { };
    };
  };
}
