{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.tlp;
  tlpExe = lib.getExe cfg.package;

  format = pkgs.formats.keyValue {
    mkKeyValue = lib.generators.mkKeyValueDefault { } "=";
    listToValue = l: "\"${toString l}\"";
  };

  configFile = format.generate "tlp.conf" cfg.settings;
in
{
  imports = [ ./providers.services.nix ];

  options.services.tlp = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [tlp](${pkgs.tlp.meta.homepage}) as a system service.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.tlp;
      defaultText = lib.literalExpression "pkgs.tlp";
      description = ''
        The package to use for `tlp`.
      '';
    };

    settings = lib.mkOption {
      type = format.type;
      default = { };
      description = ''
        `tlp` configuration. See [upstream documentation](https://linrunner.de/tlp/settings)
        for additional details.
      '';
    };

    # exposed so that providers.services.nix can name it: a unit which reads this file has
    # to name it to be rebuilt when it changes, and it cannot reach it through
    # `environment.etc`, which is where implementations put the unit itself.
    configFile = lib.mkOption {
      type = lib.types.raw;
      internal = true;
      readOnly = true;
      default = configFile;
      description = "Generated by this module, named by its units.";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.etc."tlp.conf".source = configFile;

    environment.systemPackages = [
      cfg.package
    ];

    providers.resumeAndSuspend.hooks = {
      "tlp@suspend" = {
        event = "suspend";
        action = "${tlpExe} suspend";
      };

      "tlp@resume" = {
        event = "resume";
        action = "${tlpExe} resume";
      };
    };

    services.udev.packages = [ cfg.package ];

    # TODO: revisit rules... compare with udev
    services.mdevd.hotplugRules = ''
      # handle change of power source ac/bat
      -SUBSYSTEM=power_supply;.* root:root 0600 &${tlpExe} auto

      # handle added usb devices
      # -SUBSYSTEM=usb;DEVTYPE=usb_device;.* root:root 0600 +${cfg.package}/lib/udev/tlp-usb-udev usb /sys/$DEVPATH

      # handle added usb disk devices
      # -SUBSYSTEM=block;DEVTYPE=disk;.* root:root 0600 +${cfg.package}/lib/udev/tlp-usb-udev disk /sys/$DEVPATH
    '';

  };
}
